library(profvis)
#profvis(shiny::runApp())


profvis({
	library(shiny)
	library(shinythemes)
	library(plotly)
	#library(heatmaply)
	library(reshape2)
	library(dplyr)
	library(tidyr)
	library(tibble)
	library(ggplot2)
	library(gplots)
	library(ggpubr)
	library(gridExtra)
	library(ggrepel)
	#library(dendextend)
	library(DT)
	#library(data.table)
	library(RColorBrewer)
	library(pheatmap)
	library(rgl)
	#library(car)
	library(colourpicker)
	library(VennDiagram)
	#library(pathview)
	library(factoextra)
	#library(cluster)
	#library(NbClust)
	#library(Mfuzz)
	library(openxlsx)
	#library(rmarkdown)
	library(visNetwork)
	#library(networkD3)
	#library(Hmisc)
	

source("scatter3d.R",local = TRUE)
source("pathviewfun.R",local = TRUE)
source("mfuzzfun.R",local = TRUE)

#load("db/hgnc.RData")
#load("db/kegg.pathways.RData")
#load("db/gmtlist.RData")

})

