##Fix download and color map issue with wikiprofiler.


#' @title Input specific wikipathways ID to get an output in class of wpplot.
#' @description Use wikipathways ID to open a local svg file. Then extract related information from svg file and build a wpplot class variance.
#' @param ID ID is wikipathways' ID.
#' @return A 'wpplot' object
#' @export
#' @examples
#' wpplot('WP63_117935')
wpplot <- function(ID) {
#  url <- paste0('https://classic.wikipathways.org//wpi/wpi.php?action=',
#                 'downloadFile&type=svg&pwTitle=Pathway:', ID)
  Local=F
  if (file.exists(("db/wiki_SVG/WP_Files.csv"))) {
    WP_list=read_csv("db/wiki_SVG/WP_Files.csv", show_col_types = FALSE)
    if (ID %in% WP_list$WP) {
      file1<-WP_list$file[which(ID==WP_list$WP)]
      url=str_c("db/wiki_SVG/", file1)
      cat("use local file", file1, "\n")
      Local=T
    } 
  } 
  if (Local==F){
    url0 <- 'https://www.wikipathways.org/wikipathways-assets/pathways'
    url <- sprintf("%s/%s/%s.svg", url0, ID, ID)
  }
  svg <- yulab.utils::yread(url)
  if (!any(grepl('<svg', svg[1:10]))) {
    stop("fail to read online wiki pathway file")
  }
  structure(list(
    ID = ID,
    svg = svg,
    geneExpr = NULL
  ), class = "wpplot")
}

#' @title Fill the background of gene with color according to amount of gene expression.
#' @description Generate a color array.Fill the gene then generate the legend.
#' @param p p is
#' @param value value is the amount of expression.
#' @param logFC_max, logFC range for coloring
#' @param low The color of lowest gene.
#' @param high The color of highest gene.
#' @return A 'wpplot' object
# @import org.Hs.eg.db
# @import BiocGenerics
#' @export
wp_bgfill_2025 <- function(p, value, logFC_max, high="red", mid="gray90", low="green") {
  logFC_max=as.numeric(logFC_max)
  SYMBOLS <- sub('\\s+', '', sub('.+>', '', sub('</tspan>', '', p$svg[grep('<tspan', p$svg)])))
  SYMBOLS <- SYMBOLS[is.na(suppressWarnings(as.numeric(SYMBOLS)))]
  SYMBOLS <- SYMBOLS[SYMBOLS!=""]
  if(!any(names(value) %in% SYMBOLS)){
    message("Please make sure the input gene ID type is 'SYMBOL'")
    return(p)
  }
  value <- value[names(value) %in% SYMBOLS]
  col_fun <- colorRamp2(
    breaks = c(0-logFC_max, 0, logFC_max),
    colors = c(low, mid, high))
  color=col_fun(value)
  genes <- names(value)
  for (i in seq_along(genes)) {
    #pos <- grep(genes[i], p$svg)
    pos <- grep(str_c("tspan.+>", genes[i], "</tspan>"), p$svg)
    p$svg <- replace_bg2(p$svg, pos, color[i])
  }

  lgd <- Legend(
  col_fun = col_fun,
  title = "log2FC value",
  at = c(0-logFC_max, 0, logFC_max),
  labels = c(str_c("-", logFC_max), "0", as.character(logFC_max)),
   direction = "horizontal",
  legend_width = unit(3, "cm") )
  
  p$geneExpr <- value
  return(list(p=p, lgd=lgd))
}


#' @title Add halo above gene name to get a clear view.
#' @description Add use svghalo2 function to add halo.
#' @param p An wpplot class variance.
#' @param bg.r The width of halo.
#' @param bg.col The color of halo.
#' @return A 'wpplot' object
#' @export
wp_shadowtext <- function(p, bg.r = 2, bg.col = "white") {
  if (is.null(p$geneExpr)) return(p)

  genes <- names(p$geneExpr)

  for (i in seq_along(genes)) {
    pos <- grep(genes[i], p$svg)
    p$svg <- svg_halos(p$ svg, pos, genes[i])
  }

  i <- grep("><!--Generated by the Batik Graphics2D SVG Generator-->", p$svg)

  p$svg[i] <- paste0(
    "><!--Generated by the Batik Graphics2D SVG Generator-->",
    "<style>.halo{fill:", bg.col,
    ";stroke:", bg.col, "; stroke-width:", bg.r,
    ";stroke-linejoin:round; vector-effect:non-scaling-stroke;",
    "}</style><defs id=\"genericDefs\""
  )

  return(p)
}



svg2tempfile <- function(svg) {
  f <- tempfile(fileext = ".svg")
  cat(svg, file = f)
  return(f)
}



replace_bg <- function(svg, position, color) {
  j <- rev(grep("<rect", svg[1:position]))[1]

  replace <- sub(
    "fill=.+stroke=", paste('fill="', color, '" stroke=', sep = ""),
    svg[j]
  )

  svg[j] <- replace
  return(svg)
}

replace_bg2 <- function(svg, positions, color) {
  if (is.null(positions) || all(is.na(positions)) || length(positions) == 0) {
    return(svg)
  }

  for (position in positions) {
    if (is.na(position)) next
    svg <- replace_bg(svg, position, color)
  }

  return(svg)
}